[main-monitor]
# Shell commands to execute when hotcorner is triggered,
# at least one is required.

# Command to run when cursor enters hotcorner.
# `command` is an alias for `enter_command`.
enter_command = [ "hyprswitch gui --mod-key $mod --key $key --close mod-key-release --reverse-key=key=$reverse && hyprswitch dispatch"]
# Command to run when cursor exits hotcorner.

# Locations of the hot corners.
# Options:
# - for corners: top_left, top_right, bottom_right, and bottom_left;
# - for edges: top, bottom, right, left.
locations = ["top_left"]

# Size of the hot corners in pixels, for edges the size means the width
# for vertical edges, and height for horizontal edges. The other dimension
# will be the width/height of your display - the set margin.
size = 10  # default

# Margin on the sides of the hot edges, only applicable to edge locations.
# See the comment with sizes attribute above.
margin = 20  # default

# Timeout in milliseconds before command is triggered.
timeout_ms = 250  # default

# Hex color of the corner when previewed, supports transparency. (#AARRGGBB or #RRGGBB)
# (Useful for debugging purposes when setting up several hot corners.)
color = "#FFFF0000"  # default

# Optional output config to specify what output to use.
[main-monitor.output]
# Regex to match output descriptions on.
# Regex engine is similar to RE2: https://github.com/rust-lang/regex
#
# Use `swaymsg -t get_outputs` to get a list of outputs in the format:
# Output ${NAME} '${DESCRIPTION}'
# Use `swaymsg -t get_outputs` or `hyprctl monitors` to list your outputs.
# The description of the output is what is matched.
# This often contains the output name, manufacturer, model, and serial number so
# any of those could be used for matching.
# description = "U3219Q F2XWXV2"  # default, empty means all outputs

[side-monitor]
enter_command = [ "notify-send", "left" ]
locations = ["right"]

[side-monitor.output]
description = "U2515H 9X2VY6A80A8L"
[left-top]
enter_command = [ "notify-send", "enter" ]

